namespace CatShelter.Core
{
    /// <summary>
    /// Task 60-shell-build/28: which items the first lesson points at, and on
    /// which level it runs.
    ///
    /// The lesson itself is a View thing — it dims tiles, moves a highlight and
    /// swallows taps (see View/FirstLesson.cs). What lives HERE is the only part
    /// of it that is a claim about level data: that items 1, 5 and 8 of the
    /// first pile are three of a kind and all reachable on the opening move. A
    /// lesson that points at a buried tile is a lesson the player cannot
    /// finish, and the pile file can be regenerated by the solver at any time.
    ///
    /// In Core rather than beside the view because that claim has to be
    /// CHECKED, and the check runs under `dotnet test` — build/core-tests
    /// compiles Assets/Core and Assets/Tests/Core, and nothing from Assets/View
    /// (those files need UnityEngine). Keeping the three numbers here means the
    /// guard reads the same constant the game reads, instead of a second copy
    /// that can drift from it. Tests/Core/FirstLessonPlanTests.cs is that guard.
    /// </summary>
    public static class FirstLessonPlan
    {
        /// <summary>The lesson runs on the first level and nowhere else.</summary>
        public const int LevelNumber = 1;

        /// <summary>
        /// The three props, in the order the lesson asks for them. All three are
        /// prop_board in l01_room01_pile0.json, all three carry an empty
        /// `blocked_by`, and all three sit in the top rows — near the top of the
        /// screen, above the phrase the lesson prints and clear of the thumb.
        /// </summary>
        public static readonly int[] ItemIds = { 1, 5, 8 };
    }
}
