using System;
using System.Collections.Generic;

namespace CatShelter.Core
{
    /// <summary>
    /// A level description: one pile within a room. A room holds 1–4 piles
    /// (pacing curve, task 3.12); clearing a pile clears a corner of the room.
    /// Levels are data (JSON, generated by /tools), not code.
    /// There is no move limit: see the Board docstring and
    /// reviews/2026-08-24-refactor-difficulty.md for why the parameter cannot bind.
    /// </summary>
    public sealed class Level
    {
        public int Number { get; }
        public string RoomId { get; }
        /// <summary>Which pile of the room this is, zero-based.</summary>
        public int PileIndex { get; }

        /// <summary>Items in stacking order: later entries sit on top of earlier ones.</summary>
        public IReadOnlyList<PileEntry> Pile { get; }

        public Level(int number, string roomId, int pileIndex,
                     IReadOnlyList<PileEntry> pile)
        {
            if (number < 1)
                throw new ArgumentOutOfRangeException(nameof(number));
            if (pileIndex < 0)
                throw new ArgumentOutOfRangeException(nameof(pileIndex));
            Number = number;
            RoomId = roomId ?? throw new ArgumentNullException(nameof(roomId));
            PileIndex = pileIndex;
            Pile = pile ?? throw new ArgumentNullException(nameof(pile));
        }
    }

    /// <summary>An item's position in the pile plus what covers it.</summary>
    public sealed class PileEntry
    {
        public Item Item { get; }
        /// <summary>Ids of items lying directly on top of this one.</summary>
        public IReadOnlyList<int> BlockedBy { get; }

        public PileEntry(Item item, IReadOnlyList<int> blockedBy)
        {
            Item = item ?? throw new ArgumentNullException(nameof(item));
            BlockedBy = blockedBy ?? throw new ArgumentNullException(nameof(blockedBy));
        }
    }
}
