using System;
using System.Collections.Generic;

namespace CatShelter.Core
{
    /// <summary>
    /// A level description: the pile of items and which room it belongs to.
    /// Levels are data (JSON, generated by /tools), not code — see section 9 of
    /// cat-shelter-mvp.md. There is no move limit: see the Board docstring and
    /// reviews/2026-08-24-refactor-difficulty.md for why the parameter cannot bind.
    /// </summary>
    public sealed class Level
    {
        public int Number { get; }
        public string RoomId { get; }

        /// <summary>Items in stacking order: later entries sit on top of earlier ones.</summary>
        public IReadOnlyList<PileEntry> Pile { get; }

        public Level(int number, string roomId, IReadOnlyList<PileEntry> pile)
        {
            if (number < 1)
                throw new ArgumentOutOfRangeException(nameof(number));
            Number = number;
            RoomId = roomId ?? throw new ArgumentNullException(nameof(roomId));
            Pile = pile ?? throw new ArgumentNullException(nameof(pile));
        }
    }

    /// <summary>An item's position in the pile plus what covers it.</summary>
    public sealed class PileEntry
    {
        public Item Item { get; }
        /// <summary>Ids of items lying directly on top of this one.</summary>
        public IReadOnlyList<int> BlockedBy { get; }

        public PileEntry(Item item, IReadOnlyList<int> blockedBy)
        {
            Item = item ?? throw new ArgumentNullException(nameof(item));
            BlockedBy = blockedBy ?? throw new ArgumentNullException(nameof(blockedBy));
        }
    }
}
