using System;
using System.Collections.Generic;

namespace CatShelter.Core
{
    /// <summary>
    /// A level description: one pile within a room. A room holds 1–4 piles
    /// (pacing curve, task 3.12); clearing a pile clears a corner of the room.
    /// Levels are data (JSON, generated by /tools), not code.
    /// There is no move limit: see the Board docstring and
    /// reviews/2026-08-24-refactor-difficulty.md for why the parameter cannot bind.
    /// </summary>
    public sealed class Level
    {
        public int Number { get; }
        public string RoomId { get; }
        /// <summary>Which pile of the room this is, zero-based.</summary>
        public int PileIndex { get; }

        /// <summary>Items in stacking order: later entries sit on top of earlier ones.</summary>
        public IReadOnlyList<PileEntry> Pile { get; }

        public Level(int number, string roomId, int pileIndex,
                     IReadOnlyList<PileEntry> pile)
        {
            if (number < 1)
                throw new ArgumentOutOfRangeException(nameof(number));
            if (pileIndex < 0)
                throw new ArgumentOutOfRangeException(nameof(pileIndex));
            Number = number;
            RoomId = roomId ?? throw new ArgumentNullException(nameof(roomId));
            PileIndex = pileIndex;
            Pile = pile ?? throw new ArgumentNullException(nameof(pile));

            // Rejected here rather than at Board construction, so a level that
            // cannot be won cannot be built in the first place — the Python
            // side has always validated at load time (tools/solver/schema.py).
            // Every kind must appear in triples: otherwise the pile empties
            // while items are stranded on the shelf and the win fires on an
            // unfinished board.
            var counts = new Dictionary<string, int>();
            foreach (var entry in Pile)
            {
                counts.TryGetValue(entry.Item.Kind.Id, out var seen);
                counts[entry.Item.Kind.Id] = seen + 1;
            }
            foreach (var pair in counts)
            {
                if (pair.Value % 3 != 0)
                    throw new ArgumentException(
                        $"kind '{pair.Key}' appears {pair.Value} times, " +
                        "not a multiple of three", nameof(pile));
            }

            var ids = new HashSet<int>();
            foreach (var entry in Pile)
            {
                if (!ids.Add(entry.Item.Id))
                    throw new ArgumentException(
                        $"duplicate item id {entry.Item.Id}", nameof(pile));
            }

            // Task 07 (2026-09-02): a triple completes for every 3 items that
            // ever leave the pile (kind counts are already enforced above to
            // be multiples of three), so Pile.Count / 3 is the most triples
            // this level can ever produce in a full clear. LockedAfterTriples
            // had no ceiling before this: a level with 6 items accepted 999,
            // a threshold no playthrough of that level could ever reach, and
            // Board had no way to tell that apart from a merely large but
            // legitimate one. Board's own jam guard (see its constructor)
            // catches the live symptom; this catches the bad data at the
            // door, same split as the checks above and below it.
            var maxAchievableTriples = Pile.Count / 3;
            foreach (var entry in Pile)
            {
                if (entry.Item.LockedAfterTriples > maxAchievableTriples)
                    throw new ArgumentException(
                        $"item {entry.Item.Id}: locked_after_triples " +
                        $"{entry.Item.LockedAfterTriples} exceeds {maxAchievableTriples}, " +
                        "the most triples this pile can ever complete", nameof(pile));
            }

            // The two checks below existed in tools/solver/schema.py from the
            // start and never here — found on 2026-08-27 while verifying
            // 05-ship-37-levels. The comment above cites the Python side as the
            // reason this class validates at all, and then validated less than
            // it did. A level is data read from disk at runtime, so the engine
            // that plays it is the one that has to refuse a bad one; the solver
            // refusing it in a tool nobody runs on a player's phone is no help.
            foreach (var entry in Pile)
            {
                foreach (var blocker in entry.BlockedBy)
                {
                    if (blocker == entry.Item.Id)
                        throw new ArgumentException(
                            $"item {entry.Item.Id} blocks itself", nameof(pile));
                    if (!ids.Contains(blocker))
                        throw new ArgumentException(
                            $"item {entry.Item.Id}: blocked_by {blocker} does not exist",
                            nameof(pile));
                }
            }

            RejectCycles();
        }

        /// <summary>
        /// A `blocked_by` edge points at what lies on top, so the relation has
        /// to be acyclic. A cycle leaves every item in it permanently
        /// unavailable, and the board would sit with no legal move and no
        /// outcome — the same hang <see cref="Board"/> guards against for
        /// locked items, arriving instead through a malformed file.
        ///
        /// Iterative rather than recursive: a pile is 36 to 60 items today, but
        /// this is fed by JSON from disk, and a long chain in a hand-edited file
        /// should raise an exception rather than overflow the stack.
        /// </summary>
        private void RejectCycles()
        {
            var byId = new Dictionary<int, PileEntry>();
            foreach (var entry in Pile) byId[entry.Item.Id] = entry;

            const int Visiting = 0, Done = 1;
            var mark = new Dictionary<int, int>();

            foreach (var start in Pile)
            {
                if (mark.ContainsKey(start.Item.Id)) continue;

                var stack = new Stack<(int Id, int Next)>();
                mark[start.Item.Id] = Visiting;
                stack.Push((start.Item.Id, 0));

                while (stack.Count > 0)
                {
                    var (id, next) = stack.Pop();
                    var blockers = byId[id].BlockedBy;
                    if (next >= blockers.Count)
                    {
                        mark[id] = Done;
                        continue;
                    }
                    stack.Push((id, next + 1));

                    var child = blockers[next];
                    if (mark.TryGetValue(child, out var seen))
                    {
                        if (seen == Visiting)
                            throw new ArgumentException(
                                $"cycle in blocked_by, reached again at item {child}",
                                nameof(Pile));
                        continue;
                    }
                    mark[child] = Visiting;
                    stack.Push((child, 0));
                }
            }
        }
    }

    /// <summary>An item's position in the pile plus what covers it.</summary>
    public sealed class PileEntry
    {
        public Item Item { get; }
        /// <summary>Ids of items lying directly on top of this one.</summary>
        public IReadOnlyList<int> BlockedBy { get; }

        public PileEntry(Item item, IReadOnlyList<int> blockedBy)
        {
            Item = item ?? throw new ArgumentNullException(nameof(item));
            BlockedBy = blockedBy ?? throw new ArgumentNullException(nameof(blockedBy));
        }
    }
}
