using System.Runtime.InteropServices;
using UnityEngine;

namespace CatShelter.Shell
{
    /// <summary>
    /// Task 60-shell-build/10: a sound and a tap on every move that answers the
    /// finger. Three cues — a placement, a match, and a refusal.
    ///
    /// The sounds are real files now, not runtime blips. They live in
    /// `Resources/Audio` and are generated by `tools/sound/make_sounds.py`,
    /// committed beside them: synthesised, so their licence is ours and not a
    /// question. That script carries the reasoning for how each one is built;
    /// here is only what the shell needs to know.
    ///
    /// The three are mixed against each other **in the files**, quietest to
    /// loudest: refused, place, match. So there is one volume in this class and
    /// not three, and adding a fourth cue means giving it a level in the
    /// generator rather than guessing a number at a call site.
    ///
    /// On silence:
    ///  - iOS already obeys the ring/silent switch, and no code here is what
    ///    makes it. `ProjectSettings.asset` has `muteOtherAudioSources: 0`, so
    ///    Unity runs the audio session in the Ambient category — which follows
    ///    the hardware switch and mixes under the player's own music instead of
    ///    stopping it. Changing that setting would break both, and nothing in
    ///    this class could put it back.
    ///  - Android has no silent switch over the media stream by design; its
    ///    control is the volume keys, and they work with no code either.
    ///  - <see cref="Muted"/> is ours, survives a restart, and is the switch a
    ///    settings screen should flip. It silences sound only: a phone on silent
    ///    still vibrates, and so does this.
    /// </summary>
    public sealed class Feedback : MonoBehaviour
    {
        /// <summary>Where the clips sit under Resources.</summary>
        private const string ClipFolder = "Audio/";

        private const string MutedKey = "catshelter.audio.muted";

        /// <summary>
        /// One knob for all three cues, because their balance is already baked
        /// into the files. It is the place to make the whole game quieter;
        /// louder is deliberately not offered — the files keep about 9 dB of
        /// headroom under full scale so this game is never the loudest thing in
        /// a dark room, and the player's own volume keys are the control meant
        /// for turning it up.
        /// </summary>
        private const float Volume = 1f;

        private static Feedback _instance;
        private static bool _muted;

        private AudioSource _source;
        private AudioClip _place;
        private AudioClip _match;
        private AudioClip _refused;

#if UNITY_IOS && !UNITY_EDITOR
        [DllImport("__Internal")] private static extern void CatHaptics_place();
        [DllImport("__Internal")] private static extern void CatHaptics_match();
        [DllImport("__Internal")] private static extern void CatHaptics_prepare();
#endif

        /// <summary>
        /// Sound off. Persisted, so a player who turns it off once never has to
        /// find the switch twice. Haptics are untouched by it.
        /// </summary>
        public static bool Muted
        {
            get => _muted;
            set
            {
                _muted = value;
                PlayerPrefs.SetInt(MutedKey, value ? 1 : 0);
                PlayerPrefs.Save();
            }
        }

        public static Feedback Attach(GameObject host)
        {
            if (_instance != null) return _instance;
            _instance = host.AddComponent<Feedback>();
            return _instance;
        }

        private void Awake()
        {
            _muted = PlayerPrefs.GetInt(MutedKey, 0) == 1;

            _source = gameObject.AddComponent<AudioSource>();
            _source.playOnAwake = false;
            _source.spatialBlend = 0f;   // a UI cue has no position in the room

            _place = Load("place");
            _match = Load("match");
            _refused = Load("refused");

#if UNITY_IOS && !UNITY_EDITOR
            CatHaptics_prepare();
#endif
        }

        /// <summary>One item landed on the shelf.</summary>
        public static void Place()
        {
            if (_instance == null) return;
            Play(_instance._place);
#if UNITY_IOS && !UNITY_EDITOR
            CatHaptics_place();
#endif
        }

        /// <summary>Three of a kind matched and left the shelf.</summary>
        public static void Match()
        {
            if (_instance == null) return;
            Play(_instance._match);
#if UNITY_IOS && !UNITY_EDITOR
            CatHaptics_match();
#endif
        }

        /// <summary>
        /// A tap that changed nothing: a locked tile, or a shelf with no room
        /// for it. Quieter than a placement and flat where a placement knocks —
        /// an answer, not a reprimand. A game about caring for something does
        /// not scold; but a refusal with no sound at all is indistinguishable
        /// from a tap the app never received, which is worse than either.
        ///
        /// No haptic. `Plugins/iOS/CatHaptics.swift` exports a placement tap and
        /// a match tap and nothing else, and that file belonged to another pass.
        /// A `.rigid` generator beside those two is what this would want.
        ///
        /// NOT YET CALLED. Its one call site is the refusal branch of
        /// `DebugGameView.Take` — the branch that already logs "tap refused" and
        /// calls `Flinch(source)` — and that file was another worker's this
        /// pass. One line, beside the `Flinch`.
        /// </summary>
        public static void Refused()
        {
            if (_instance == null) return;
            Play(_instance._refused);
        }

        private static void Play(AudioClip clip)
        {
            if (_muted || clip == null) return;
            _instance._source.PlayOneShot(clip, Volume);
        }

        /// <summary>
        /// A missing clip costs the cue and nothing else — the move still
        /// happens and the haptic still fires. Worth a warning all the same:
        /// from outside the app, a silent cue and a failed import look the same.
        /// </summary>
        private static AudioClip Load(string name)
        {
            var clip = Resources.Load<AudioClip>(ClipFolder + name);
            if (clip == null)
                Debug.LogWarning($"[Feedback] no clip at Resources/{ClipFolder}{name} " +
                                 "— that cue will be silent");
            return clip;
        }
    }
}
