import Foundation
import Vision
import ImageIO
import CoreGraphics

// tools/vision-probe: 50-photo/05-vision-plugin/NOTES.md cites "the macOS
// probe" as the source of the recognition table it reports, and no such
// program existed anywhere in this repository — the numbers were asserted in
// prose with nothing to re-run. This reconstructs it: VNRecognizeAnimalsRequest,
// the same API Plugins/iOS/CatVision.swift calls, over a folder of images,
// printing one JSON line per image (file, ok, error, every detection sorted by
// confidence, best.identifier/confidence).
//
// This is NOT the shipped plugin. No @_cdecl bridge, no C#/IL2CPP marshalling,
// and Vision on macOS is not guaranteed to run the same model Vision runs on
// an iPhone's neural engine — see 05-vision-plugin/VERIFY.md for why that gap
// matters. What this buys back is reproducibility: the numbers this project
// quotes about its own hook can now be regenerated by anyone with a Mac,
// checked against what NOTES.md already claims, instead of trusted on prose.

struct Detection: Encodable {
    let identifier: String
    let confidence: Double
}

struct ImageResult: Encodable {
    let file: String
    let ok: Bool
    let error: String?
    let detections: [Detection]

    var best: Detection? { detections.first }
}

func orientationOf(_ source: CGImageSource) -> CGImagePropertyOrientation {
    // Mirrors CatVision.swift's orientationRaw == 0 branch: read EXIF, or
    // assume .up if there is none. This tool has no caller passing an
    // explicit orientation, so it always takes the file's own metadata.
    guard let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
          let exif = properties[kCGImagePropertyOrientation] as? UInt32,
          let orientation = CGImagePropertyOrientation(rawValue: exif) else {
        return .up
    }
    return orientation
}

func recognise(path: String) -> ImageResult {
    let file = (path as NSString).lastPathComponent
    guard let data = FileManager.default.contents(atPath: path) else {
        return ImageResult(file: file, ok: false, error: "could not read file", detections: [])
    }
    guard let source = CGImageSourceCreateWithData(data as CFData, nil),
          let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else {
        return ImageResult(file: file, ok: false, error: "not a decodable image", detections: [])
    }

    let orientation = orientationOf(source)
    let request = VNRecognizeAnimalsRequest()
    let handler = VNImageRequestHandler(cgImage: image, orientation: orientation, options: [:])
    do {
        try handler.perform([request])
    } catch {
        return ImageResult(file: file, ok: false,
                            error: "vision failed: \(error.localizedDescription)", detections: [])
    }

    var detections: [Detection] = []
    for observation in request.results ?? [] {
        guard let label = observation.labels.first else { continue }
        detections.append(Detection(identifier: label.identifier, confidence: Double(label.confidence)))
    }
    detections.sort { $0.confidence > $1.confidence }
    return ImageResult(file: file, ok: true, error: nil, detections: detections)
}

guard CommandLine.arguments.count > 1 else {
    FileHandle.standardError.write("usage: vision-probe <directory-of-images>\n".data(using: .utf8)!)
    exit(1)
}
let directory = CommandLine.arguments[1]
let fm = FileManager.default
guard let entries = try? fm.contentsOfDirectory(atPath: directory) else {
    FileHandle.standardError.write("could not list \(directory)\n".data(using: .utf8)!)
    exit(1)
}
let images = entries.filter {
    $0.hasSuffix(".jpg") || $0.hasSuffix(".jpeg") || $0.hasSuffix(".png")
}.sorted()

let encoder = JSONEncoder()
for name in images {
    let result = recognise(path: (directory as NSString).appendingPathComponent(name))
    if let data = try? encoder.encode(result), let line = String(data: data, encoding: .utf8) {
        print(line)
    }
}
